In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import torch
from tqdm import tqdm
import statsmodels.api as sm
import plotly.graph_objects as go
import cvxpy as cvx
import scipy
import ot as ot
import multiprocessing as mp
import time
import concurrent.futures
import functools
import sys
import os
import numpy as np
from scipy.stats import norm
from classesv2 import *

In [8]:
#20,500 I_logm
params = dict(seed=5,
              n=100, 
              d=3,
              p=5,
              model="MNL",
              theta_seed=1233,
              num_epochs=20,
              init_mu="logm",
              B=5,
              estimator="ours")



os.system('python CLIrunner.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from MNL model..
Generating data from MNL model..
Generating data from MNL model..
Generating data from MNL model..
Generating data from MNL model..
hyperparameters : 
  
seed :  [3518] 
n :  100 
d :  3 
p :  5 
model :  MNL 
seed_theta :  1233 
num_epochs :  20 
initial_mu :  logm 
B :  5 
Estimator :  ours
number of estimations B :  5
average (over parameters) Error Square : 0.004603146
average (over parameters) Error : -0.016557653
average (over parameters) Variance : 0.0014438242105112332
average (over parameters) absolute difference : 0.041626357
average time 0.7019450664520264


0

In [12]:

params = dict(seed=5,
              n=100, 
              d=3,
              p=5,
              model="MNL",
              theta_seed=1233,
              num_epochs=5,
              init_mu=None,
              B=5,
              estimator="PBinit")



os.system('python PB-CLIrunner.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from MNL model..
Initializing the theta by parallel PB
One parallel iteration, Finished in 3.21 second(s)
One parallel iteration, Finished in 3.21 second(s)
One parallel iteration, Finished in 3.25 second(s)
One parallel iteration, Finished in 3.2 second(s)
One parallel iteration, Finished in 3.23 second(s)
time spent in 1 Bootstrap sample, (DGP model='mixture')  21.576503038406372
Generating data from MNL model..
Initializing the theta by parallel PB
One parallel iteration, Finished in 3.22 second(s)
One parallel iteration, Finished in 3.23 second(s)
One parallel iteration, Finished in 3.23 second(s)
One parallel iteration, Finished in 3.35 second(s)
One parallel iteration, Finished in 3.27 second(s)
time spent in 1 Bootstrap sample, (DGP model='mixture')  21.7257661819458
Generating data from MNL model..
Initializing the theta by parallel PB
One parallel iteration, Finished in 3.21 second(s)
One parallel iteration, Finished in 3.24 second(s)
One parallel iteration, Fi

0

In [9]:
#20,1000 I_logm
params = dict(seed=6,
              n=100, 
              d=10,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=50,
              init_mu="logm",
              B=5,
              estimator="ours")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [9346] 
n :  100 
d :  10 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  50 
initial_mu :  logm 
B :  5 
Estimator :  ours
number of estimations B :  5
average (over parameters) Error Square : 0.041116882
average (over parameters) Error : 0.0059958072
average (over parameters) Variance : 0.0345784117354167
average (over parameters) absolute difference : 0.14391217
average time 3.274390935897827


0

In [8]:
#50,1000 I_logm
params = dict(seed=7,
              n=1000, 
              d=50,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=50,
              init_mu="logm",
              B=10,
              estimator="ours")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )


Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [2187] 
n :  1000 
d :  50 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  50 
initial_mu :  logm 
B :  10 
Estimator :  ours
number of estimations B :  10
average (over parameters) Error Square : 0.034806598
average (over parameters) Error : -0.030128801
average (over parameters) Variance : 0.02844125036403387
average (over parameters) absolute difference : 0.14618394
average time 232.78280210494995


0

# $\hat{\theta}_P$

In [13]:
#20,500 P
params = dict(seed=5,
              n=500, 
              d=20,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=0,
              init_mu="zero",
              B=5,
              estimator="ours")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [1725] 
n :  500 
d :  20 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  0 
initial_mu :  zero 
B :  5 
Estimator :  ours
number of estimations B :  5
average (over parameters) Error Square : 0.72603494
average (over parameters) Error : 0.023293052
average (over parameters) Variance : 0.014042877046744671
average (over parameters) absolute difference : 0.6511053
average time 0.6012468338012695


0

In [14]:
#20,1000 P
params = dict(seed=5,
              n=1000, 
              d=20,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=0,
              init_mu="zero",
              B=5,
              estimator="ours")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [6126] 
n :  1000 
d :  20 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  0 
initial_mu :  zero 
B :  5 
Estimator :  ours
number of estimations B :  5
average (over parameters) Error Square : 0.7154341
average (over parameters) Error : 0.028645286
average (over parameters) Variance : 0.004905562770867734
average (over parameters) absolute difference : 0.6485541
average time 1.1938180923461914


0

In [15]:
#50,1000 I_zero
params = dict(seed=5,
              n=1000, 
              d=50,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=0,
              init_mu="zero",
              B=5,
              estimator="ours")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [4395] 
n :  1000 
d :  50 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  0 
initial_mu :  zero 
B :  5 
Estimator :  ours
number of estimations B :  5
average (over parameters) Error Square : 0.81257254
average (over parameters) Error : -0.04032336
average (over parameters) Variance : 0.002520335311717359
average (over parameters) absolute difference : 0.7365426
average time 2.8036739826202393


0

# $\hat{\theta}_{MLE}$

In [17]:
#20,500 MLE
params = dict(seed=5,
              n=500, 
              d=20,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=0,
              init_mu="zero",
              B=5,
              estimator="MLE")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [7638] 
n :  500 
d :  20 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  0 
initial_mu :  zero 
B :  5 
Estimator :  MLE
number of estimations B :  5
average (over parameters) Error Square : 0.00611735
average (over parameters) Error : 0.0037405048
average (over parameters) Variance : 0.004995095328746601
average (over parameters) absolute difference : 0.05463783
average time 16.413415908813477


0

In [18]:
#20,1000 MLE
params = dict(seed=5,
              n=1000, 
              d=20,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=0,
              init_mu="zero",
              B=5,
              estimator="MLE")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [6385] 
n :  1000 
d :  20 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  0 
initial_mu :  zero 
B :  5 
Estimator :  MLE
number of estimations B :  5
average (over parameters) Error Square : 0.0032857433
average (over parameters) Error : -0.0051061823
average (over parameters) Variance : 0.002549183101438333
average (over parameters) absolute difference : 0.041096687
average time 52.4750599861145


0

In [19]:
#50,1000 MLE
params = dict(seed=5,
              n=1000, 
              d=50,
              p=5,
              model="mixture",
              theta_seed=1233,
              num_epochs=0,
              init_mu="zero",
              B=5,
              estimator="MLE")



os.system('python denemeEst7.py '    +
         str(params['seed'])         + ' ' + \
         str(params['n'])            + ' ' + \
         str(params['d'])            + ' ' + \
         str(params['p'])            + ' ' + \
         str(params['model'])        + ' ' + \
         str(params['theta_seed'])   + ' ' + \
         str(params['num_epochs'])   + ' ' + \
         str(params['init_mu'])      + ' ' + \
         str(params['B'])            + ' ' + \
         str(params['estimator']) )

Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
Generating data from Mixture MNL..
hyperparameters : 
  
seed :  [8437] 
n :  1000 
d :  50 
p :  5 
model :  mixture 
seed_theta :  1233 
num_epochs :  0 
initial_mu :  zero 
B :  5 
Estimator :  MLE
number of estimations B :  5
average (over parameters) Error Square : 0.031572938
average (over parameters) Error : 0.025706893
average (over parameters) Variance : 0.02680920060379771
average (over parameters) absolute difference : 0.14246151
average time 108.15089106559753


0

In [ ]:
python denemeEst7.py params['seed'] params['n'] params['d'] params['p'] params['model'] \
                        params['theta_seed'] params['num_epochs'] params['init_mu'] params['B'] params['estimator']

In [2]:
# DGP MNL, Estimator ours logm

seed = 2
n = 100
d = 5
p = 5
model = 'MNL'
seed_theta= 1233
num_epochs = 60 
initial_mu = 'logm'
B = 1

data_ ,thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])
PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit(num_epochs= num_epochs,
                                                                             initial_mu = 'logm',
                                                                             verbose = False)
print(PARALLEL_normalized_theta_hat)





Generating data from MNL model..
[[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
Sample Size :  100
[[ 0.          0.53121532  0.33751938 -0.13117037 -0.84637855]
 [ 0.          0.23016779 -0.48381911  0.494403   -1.59609569]
 [ 0.          0.69881825 -1.3095202  -0.62070169 -1.49165757]
 [ 0.          0.81473787  0.47656317  0.34711241 -0.46209852]
 [ 0.          1.25447758 -1.15133328 -0.17457522  1.40124579]]


In [3]:
# DGP MNL, Estimator ours- zero

seed = 2
n = 100
d = 5
p = 5
model = 'MNL'
seed_theta= 1233
num_epochs = 60 
initial_mu = 'zero'
B = 1

data_ ,thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])
PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit(num_epochs= num_epochs,
                                                                             initial_mu = 'logm',
                                                                             verbose = False)
print(PARALLEL_normalized_theta_hat)



Generating data from MNL model..
[[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
Sample Size :  100
[[ 0.          0.53121532  0.33751938 -0.13117037 -0.84637855]
 [ 0.          0.23016779 -0.48381911  0.494403   -1.59609569]
 [ 0.          0.69881825 -1.3095202  -0.62070169 -1.49165757]
 [ 0.          0.81473787  0.47656317  0.34711241 -0.46209852]
 [ 0.          1.25447758 -1.15133328 -0.17457522  1.40124579]]


In [4]:
# DGP Poisson, Estimator ours - logm 

seed = 2
n = 100
d = 5
p = 5
model = 'Po'
seed_theta= 1233
num_epochs = 60 
initial_mu = 'logm'
B = 1

data_, muTRUE_vec, thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])
PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit(num_epochs= num_epochs,
                                                                             initial_mu = 'logm',
                                                                             verbose = False)
print(PARALLEL_normalized_theta_hat)





Generating data from Poisson..
[[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
Sample Size :  97
[[ 0.          0.53850331  0.29306442 -0.05969786 -1.00865932]
 [ 0.          0.11073977 -0.59337902  0.31990113 -1.62987448]
 [ 0.          0.54719669 -1.29681859 -0.54021097 -1.60412245]
 [ 0.          0.92784373  0.69721951  0.5380951  -0.54014755]
 [ 0.          1.31062113 -1.17774633 -0.21437752  1.33343082]]


In [5]:
# DGP Poisson, Estimator ours - zero 

seed = 2
n = 100
d = 5
p = 5
model = 'Po'
seed_theta= 1233
num_epochs = 60 
initial_mu = 'zero'
B = 1

data_, muTRUE_vec, thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])
PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit(num_epochs= num_epochs,
                                                                             initial_mu = 'logm',
                                                                             verbose = False)
print(PARALLEL_normalized_theta_hat)




Generating data from Poisson..
[[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
Sample Size :  97
[[ 0.          0.53850331  0.29306442 -0.05969786 -1.00865932]
 [ 0.          0.11073977 -0.59337902  0.31990113 -1.62987448]
 [ 0.          0.54719669 -1.29681859 -0.54021097 -1.60412245]
 [ 0.          0.92784373  0.69721951  0.5380951  -0.54014755]
 [ 0.          1.31062113 -1.17774633 -0.21437752  1.33343082]]


In [6]:
# DGP Poisson, Estimator Taddy

seed = 2
n = 100
d = 5
p = 5
model = 'Po'
seed_theta= 1233
num_epochs = 0
initial_mu = 'logm'
B = 1

data_, muTRUE_vec, thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])
PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit(num_epochs= num_epochs,
                                                                             initial_mu = 'logm',
                                                                             verbose = False)
print(PARALLEL_normalized_theta_hat)




Generating data from Poisson..
[[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
Sample Size :  97
[[ 0.          0.14298883  0.1066302  -0.02663039  0.00906032]
 [ 0.          0.02764839 -0.15968479  0.02090938 -0.40770202]
 [ 0.          0.10605581 -0.13369939 -0.0504104  -0.17874776]
 [ 0.          0.11992622  0.04100879  0.04724423 -0.28916634]
 [ 0.          0.15701667 -0.04711355  0.00567905  0.39219163]]


In [7]:
# DGP MNL, Estimator Taddy

seed = 2
n = 100
d = 5
p = 5
model = 'MNL'
seed_theta= 1233
num_epochs = 0 
initial_mu = 'logm'
B = 1

data_ ,thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])
PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit(num_epochs= num_epochs,
                                                                             initial_mu = 'logm',
                                                                             verbose = False)
print(PARALLEL_normalized_theta_hat)



Generating data from MNL model..
[[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
Sample Size :  100
[[ 0.          0.0775736   0.06274242 -0.00753095 -0.08687916]
 [ 0.          0.03607867 -0.06380439  0.05730698 -0.19974513]
 [ 0.          0.07670339 -0.1611418  -0.06236296 -0.2095911 ]
 [ 0.          0.12015709  0.06629401  0.01196965 -0.04340488]
 [ 0.          0.14123889 -0.16735076 -0.00090536  0.15876446]]


In [6]:
# DGP MNL, Estimator Newton Raphson
seed = 2
n = 1000
d = 40
p = 5
model = 'MNL'
seed_theta= 1233
num_iter = 10 
initial_mu = 'logm'
B = 1

data_ ,thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])

PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit_NewtonRaphson(num_iter=10)

print(PARALLEL_normalized_theta_hat)

Generating data from MNL model..
[[ 0.00000000e+00  5.21968041e-01  3.52756423e-01 -7.44933961e-02
  -9.24773585e-01 -3.14078635e-01 -1.62438812e-01 -8.73038265e-01
   4.06312628e-02 -1.97735796e+00  5.55697565e-01  1.08449386e+00
  -7.76317388e-01 -1.32688246e-01 -1.04130580e+00 -1.54178495e+00
  -7.36343504e-01 -1.03365489e+00 -1.18268215e+00 -2.09017773e+00
  -9.50003963e-01  3.85242447e-01 -2.13577510e+00 -1.13007121e+00
   4.32150493e-01 -1.92003182e+00 -4.84396773e-01  8.07879926e-01
  -3.74792423e-01 -4.36143262e-01  5.36910378e-01 -1.04613264e+00
  -1.56110812e+00  5.11786066e-01 -1.17966247e+00 -3.21990596e-01
  -1.36345200e+00 -1.44985191e+00  1.89676394e-01 -1.84954167e+00]
 [ 0.00000000e+00  1.51560131e+00 -2.28642862e-01  3.26456496e+00
   1.87937364e+00  1.72670132e+00  1.22182446e+00  5.06666168e-01
   4.07506261e-01  9.03819902e-01  1.72798236e+00  2.63955652e+00
   6.67185877e-03  2.36509272e+00  1.73091021e-01  1.40186039e+00
  -2.10604000e-01  2.26582381e+00  5.90965

In [10]:
# DGP Po, Estimator Newton Raphson
seed = 2
n = 10000
d = 16
p = 5
model = 'Po'
seed_theta= 1233
num_iter = 10 
initial_mu = 'logm'
B = 1

data_, muTRUE_vec, thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

PARALLEL_mdl = MDR_v9(textData_obj= data_)
print(normalized_thetaTRUE_mat)
print('Sample Size : ', data_.C.shape[0])

PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit_NewtonRaphson(num_iter=10)

print(PARALLEL_normalized_theta_hat)

Generating data from Poisson..
[[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359 -0.31407863
  -0.16243881 -0.87303826  0.04063126 -1.97735796  0.55569756  1.08449386
  -0.77631739 -0.13268825 -1.0413058  -1.54178495]
 [ 0.         -0.29731139 -0.44633864 -1.35383423 -0.21366046  1.12158595
  -1.3994316  -0.3937277   1.168494   -1.18368831  0.25194673  1.54422343
   0.36155108  0.30020024  1.27325388 -0.30978914]
 [ 0.          2.07289419  0.38144565  1.23911752  0.19765612  0.11125621
   1.75078451 -0.28843355 -0.50207704  1.01352427 -0.7307199   2.76248793
   1.3772966   1.22462428  0.71974743  0.00458913]
 [ 0.          0.49631364  1.3204761   2.23205026 -0.4008344   1.95758646
  -0.23441524  0.99435413 -0.61811026  1.85831755  0.18345892  2.14480296
   2.21171506  1.10227456  1.59688885  1.5311908 ]
 [ 0.         -0.45344672 -1.89346179 -2.1939368  -1.77611503 -1.76638775
  -0.43556474 -1.71108137 -1.88105188 -1.89379761  0.53067864 -1.43338294
  -1.00070229 -1.75558269

LinAlgError: Singular matrix

In [ ]:
def get_sd(V, theta_vec, mu_vec):    
    p = V.shape[1]
    a = np.exp(V @ theta_vec + mu_vec)
    A = a.reshape(-1,1) @ np.ones((1,p))
    sd = self.V.T @ ( A * self.V)
    return(sd)

In [14]:
# DGP MNL, Estimator MLE-Bohning 92


seed = 2
n = 100
d = 5
p = 5
model = 'MNL'
seed_theta= 1233
num_epochs = 60 
#initial_mu = 'logm'
B = 1

data_ ,thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)

# MLE through Bohning

mdl = nll_l_cvm(data_)
optimizer = torch.optim.AdamW(mdl.parameters(), lr=1e-1)

XtXinv = np.linalg.inv(np.transpose(mdl.V) @ mdl.V) #(p,p)
E = np.identity(d) #(d,d)
B_inv = 2 * np.kron( E + np.ones((d, d)), XtXinv) #(dp,dp)

for steps in range(1000):  
    loss = mdl() 
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    # get the gradient:
    fd = mdl.theta_layer.weight.grad #(d,p)
    fd = fd.reshape(-1) #(dp,) # order of reshape could be f.ing up
    
    # Change the following line to Bohning92 
    # optimizer.step()
    params = mdl.theta_layer.weight.reshape(-1).detach().numpy()
    params = params - B_inv @ fd.numpy()
    with torch.no_grad():
        mdl.theta_layer.weight = torch.nn.parameter.Parameter(torch.from_numpy(params.reshape(d,p)))
    
normalized_theta_hat_mle = normalize(mdl.theta_layer.weight.transpose(1,0).detach().numpy())
print('True theta matrix\n',normalized_thetaTRUE_mat)
print('MLE-Bohning estimate : \n', normalized_theta_hat_mle)


Generating data from MNL model..
True theta matrix
 [[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
MLE estimate : 
 [[ 0.          0.53130197  0.33756036 -0.13122796 -0.84667025]
 [ 0.          0.23019777 -0.48388662  0.49452557 -1.59652165]
 [ 0.          0.69902715 -1.30981461 -0.6208597  -1.49194693]
 [ 0.          0.81498761  0.47671657  0.34727126 -0.46234282]
 [ 0.          1.2548616  -1.15161919 -0.17469612  1.40182183]]


In [17]:
# DGP MNL, Estimator MLE

seed = 2
n = 1000
d = 5
p = 5
model = 'MNL'
seed_theta= 1233
num_epochs = 0 
initial_mu = 'logm'
B = 1

data_ ,thetaTRUE_mat = generate_DATA(seed = seed, n = n, d = d, p = p, model = model, seed_theta = seed_theta)

normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)


mdl = nll_l_cvm(data_)
optimizer = torch.optim.AdamW(mdl.parameters(), lr=1e-3)

for steps in range(10000):  
    loss = mdl() 
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    
print('True theta matrix',normalized_thetaTRUE_mat)
normalized_theta_hat_mle = normalize(mdl.theta_layer.weight.transpose(1,0).detach().numpy())
print('MLE estimate : ', normalized_theta_hat_mle)

Generating data from MNL model..
True theta matrix [[ 0.          0.52196804  0.35275642 -0.0744934  -0.92477359]
 [ 0.          0.15163982 -0.55895963  0.3547099  -1.66327933]
 [ 0.          0.5287963  -1.33201495 -0.68838581 -1.59700336]
 [ 0.          0.80544145  0.50813006  0.35910281 -0.54839278]
 [ 0.          1.33524641 -1.18577114 -0.18006724  1.38215446]]
MLE estimate :  [[ 0.          0.50887571  0.34237892 -0.06759596 -0.92303195]
 [ 0.          0.15047828 -0.55068691  0.37035346 -1.67653612]
 [ 0.          0.51967532 -1.35237729 -0.73039186 -1.60380049]
 [ 0.          0.81706386  0.50320024  0.36432925 -0.56810225]
 [ 0.          1.33395134 -1.17334004 -0.15858593  1.3929312 ]]


In [12]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)
class nll_l_cvm(nn.Module):

    def __init__(self, data_):
        super().__init__()
        self.C = torch.from_numpy(data_.C) #(n,d)
        self.V = torch.from_numpy(data_.V) #(n,p)
        self.m = torch.from_numpy(data_.m).to(torch.float64) #(m,)
        
        self.n = self.C.shape[0]
        self.d = self.C.shape[1]
        self.p = self.V.shape[1]
        
        self.theta_layer = nn.Linear(self.p, self.d, dtype=torch.float64 ,bias=False)

    def forward(self):
        eta_mat = self.theta_layer(self.V) #(n,d)
        eta_vec = torch.sum(eta_mat, 1 )
    
        lse_eta_vec = torch.logsumexp(eta_mat,axis = 1)
    
        q1 = self.m @ lse_eta_vec
        q2 =  torch.sum(torch.diag(self.C@(torch.transpose(eta_mat,1,0))))
        loss = q1 - q2 

        return(loss/self.n)

In [18]:
mdl = nll_l_cvm(data_)
optimizer = torch.optim.AdamW(mdl.parameters(), lr=1e-3)

for steps in range(10000):  
    loss = mdl() 
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()


In [19]:
normalized_theta_hat_mle = normalize(mdl.theta_layer.weight.transpose(1,0).detach().numpy())
normalized_theta_hat_mle

array([[ 0.        ,  0.50888273,  0.34238274, -0.06759892, -0.92305256],
       [ 0.        ,  0.15042818, -0.55071259,  0.37034099, -1.67658932],
       [ 0.        ,  0.51968489, -1.35235237, -0.7303689 , -1.60378069],
       [ 0.        ,  0.81708564,  0.50321107,  0.36433342, -0.56806741],
       [ 0.        ,  1.3339997 , -1.17337544, -0.15856092,  1.39296975]])

In [20]:
err_sq_mle = (normalized_theta_hat_mle - normalized_thetaTRUE_mat)**2
err_sq_mle.mean()

0.00017737510760256357

In [16]:
err_sq = (PARALLEL_normalized_theta_hat - normalized_thetaTRUE_mat)**2
err_sq.mean()

NameError: name 'PARALLEL_normalized_theta_hat' is not defined

In [18]:
# import numpy as np
import matplotlib.pyplot as plt 
import torch
from tqdm import tqdm
import statsmodels.api as sm
import plotly.graph_objects as go
import cvxpy as cvx
import scipy
import multiprocessing as mp
import time
import concurrent.futures
import functools
from classesv2 import *
# Command line inputting
import sys


######################################
seed = 5
n = 1000

d = 80
p = 5

model = 'Po'
seed_theta = 1233

num_epochs = 50
initial_mu = 'logm'
B = 1

b_idx_theta_list = [] 
sq_diff = []
abs_diff = []
_diff = []
time_list = []
random_start_seed = np.random.randint(10000, size = 1)

for b in range(B):
    print(b)
    data_, thetaTRUE_mat = generate_DATA(seed =random_start_seed+b, n = n, d = d, p = p, model = model, seed_theta= seed_theta)
    normalized_thetaTRUE_mat = normalize(thetaTRUE_mat)
    PARALLEL_mdl = MDR_v9(textData_obj= data_)
    PARALLEL_mdl.initial_mu = initial_mu 
    PARALLEL_mdl.mu_vec = np.log(PARALLEL_mdl.m).reshape(-1,1)
    words = list(np.arange(PARALLEL_mdl.d))
    try:
        start = time.time()
        PARALLEL_normalized_theta_hat, PARALLEL_theta_hat = PARALLEL_mdl.fit(num_epochs= num_epochs,
                                                                                     initial_mu = 'logm',
                                                                                     verbose = False)
        end = time.time()
        time_took = end - start
        #print("time spent ",time_took)

    except:
        print("Oops!", sys.exc_info()[0], "occurred.")
        print("Skipping this seed.")
        continue
    
    b_idx_theta_list.append(PARALLEL_normalized_theta_hat)
    sq_diff.append( (PARALLEL_normalized_theta_hat - normalized_thetaTRUE_mat)**2 )
    abs_diff.append(  np.average(np.abs(PARALLEL_normalized_theta_hat - normalized_thetaTRUE_mat) ))
    _diff.append(  np.average(PARALLEL_normalized_theta_hat - normalized_thetaTRUE_mat))
    time_list.append(time_took)
    print("average (over parameters) Error Square : "  + str(np.asarray(sq_diff,  dtype=np.float32).mean()))
    print("average (over parameters) absolute difference : " + str(np.asarray(abs_diff, dtype=np.float32).mean()))
    print("average time " + str(np.mean(time_took)))

print('hyperparameters : \n ', 
'\nseed : ', random_start_seed, 
'\nn : ', n,
'\nd : ', d,
'\np : ', p,
'\nmodel : ' , model,
'\nseed_theta : ', seed_theta,
'\nnum_epochs : ', num_epochs,
'\ninitial_mu : ', initial_mu,
'\nB : ', B)

print('number of estimations B : ', B)
print("average (over parameters) Error Square : "  + str(np.asarray(sq_diff,  dtype=np.float32).mean()))
print("average (over parameters) Error : "  + str(np.asarray(_diff,  dtype=np.float32).mean()))
print("average (over parameters) Variance : "  + str(get_variance_from_b_idx_theta_list(b_idx_theta_list)))
print("average (over parameters) absolute difference : " + str(np.asarray(abs_diff, dtype=np.float32).mean()))
print("average time " + str(np.mean(time_took)))

0
Generating data from Poisson..


ValueError: too many values to unpack (expected 2)

In [14]:
print("average (over parameters) Error Square : "  + str(np.asarray(sq_diff,  dtype=np.float32).mean()))


average (over parameters) Error Square : 0.013760276


In [15]:
print("average (over parameters) absolute difference : " + str(np.asarray(abs_diff, dtype=np.float32).mean()))


average (over parameters) absolute difference : 0.09098639


In [16]:
print("average time " + str(np.mean(time_took)))

average time 381.23040533065796
